FORMAT: 1A

# Notifications

API to enable the server to send push notifications to mobile devices

## Notifications [/v1/notifications]

The main path for the notifications resource API

## Get notification settings [GET /v1/notifications]

Retrieve a list supported notifications and their current state and information

+ Response 200 (application/json)

    [
        {
            "name" : "Sleep Score",
            "type" : "SLEEP_SCORE",
            "enabled" : true,
            "schedule" : {
                "hour" : 23,
                "minute" : 30
            }
        }
    ]

## Update notification settings [PUT /v1/notifications]

Update notification settings

+ Request
    
    [
        {
            "name" : "Sleep Score",
            "type" : "SLEEP_SCORE",
            "enabled" : false,
            "schedule" : {
                "hour" : 23,
                "minute" : 30
            }
        }
    ]

## Store the token [POST /v1/notifications/registration]

API used to update the server with the push notification token retrieved through
the push notification service for the platform

+ Request 
    
    {
        "token" : <the token>,
        "os" : <android | ios>,
        "version" : <platform os version>,
        "app_version" : <version of the app, 2.0.4>
    }

+ Response 204 (application/json)

## Delete the token [DELETE /v1/notifications/registration]

API to remove a registered token.  Typically not needed

+ Request

    {
        "token" : <the token>,
        "os" : <android | ios>,
        "version" : <platform os version>,
        "app_version" : <version of the app, 2.0.4>
    }

+ Response 204 (application/json)

## Token

+ token (string, required) - the string representation of the push token
+ os (enum, required) - either android or ios
    + Members
        + android
        + ios
+ version (string, required) - iOS or Android OS version
+ app_version (string, required) - the application version

## NotificationSetting (object)

+ name (string, required) - localized name for this type of notification
+ type (enum, required) - string value indicating notification type
    + Members
        + SLEEP_SCORE
        + SYSTEM
        + SLEEP_REMINDER
+ enabled (boolean, required) - true if enabled, false otherwise
+ schedule (object, optional) - object representing the set schedule for the notification

## NotificationSchedule (object)

+ hour (number, required) - a number between 0 - 24 representing the hour of the day
+ minute (number, required) - a number betwen 0 - 60 representing the minute of the day
