FORMAT: 1A

# Timeline v2
Timeline is an API allowing consumers to view detailed and summarized data about a night of sleep.

## Timeline [/timeline/{date}]

+ Attributes
    + score: `78` (required, number) - A value quantifying sleep quality
    + `score_condition`: `ALERT` (required, string) - A relative value for sleep quality
    + message: `You were asleep for 7.8 hours and sleeping soundly for 5.4 hours.` (required, string)
    + date: `2015-03-11` (required, string) - Date for the night of sleep
    + segments (array[Event], required)
    + metrics (array[Metric])

### View a night's sleep data [GET]

+ Response 200 (application/json)
    + Attributes (Timeline)

## Event [/timeline/{date}/event{?event_type,event_timestamp,new_event_time}]

+ Parameters
    + date: `2015-04-12` (string, required) - An ISO8601 formatted date
    + `event_type`: `ALARM_RANG` (string, required) - The type of the event
    + `event_timestamp`: `1432768812` (number, required) - The unix timestamp of the time the event occured

+ Attributes
    + timestamp: `1432768812` (number, required)
    + `timezone_offset`: `860000` (number, required) - Offset between timestamp and user's local time in milliseconds
    + duration: `27000` (number, required) - Duration of the event in seconds
    + message: `You were moving around` (string)
    + `sleep_depth`: `24` (number) - Depth of sleep during the event
    + `sleep_state`: `LIGHT` (string, required) - State of sleep depth or wakefulness
    + `event_type`: `GENERIC_MOTION` (string) - Type of the event which occurred

### Amend the time of an event [PATCH]

+ Parameters
    + `new_event_time`: `14:52` (string, required) The corrected time submitted by the user

+ Response 202

### Mark an event as correct [PUT]

+ Response 202

### Delete an event [DELETE]

+ Response 202

## Data Structures

### Metric

+ name: `time_to_sleep` (string, required) - type of statistic
+ value: `46` (string, required) - raw value
+ unit: `min` (string, required) - unit of raw value
+ condition: `ALERT` - quality of raw value
